### ISSUE TITLE
Registration sonrası otomatik login

### ISSUE THREAD

**Issue by ozziest** [sausozluk/api#23]
Olmuyor. Olmalı mı?

**Comment by okan** [comment]
@ozziest Register sonrası mı abi?

**Comment by ozziest** [comment]
@okan evet evet ben açamamışım başlığı. :)

**Comment by okan** [comment]
@ozziest düzelttim abi, umarım hislerine tercih olmuşumdur. :)
@erayarslan sana paslıyorum 👍

**Comment by erayarslan** [comment]
registerden token dönerse halledebilirim.

```
{
  "success": true,
  "session": {
    "user_id": 2,
    "token": "adasdasd"
  }
}
```

gibi.

**Comment by okan** [comment]
registerden token dönüyor.

```
{
  "success": true,
  "data": {
    "user_id": 2,
    "token": "adasdasd"
  }
}
```

gibi.
