### ISSUE TITLE
Arama Karışıklığı

### ISSUE THREAD

**Issue by ozziest** [sausozluk/api#45]
Kayıtlı olan dr schultz  hakkında başlık açmak isterken beni doğrudan dr schultz  kullanıcısının sayfasına yönlendiriyor.  Bu bir hata mıdır sayın yöneticiler?

**Comment by ozziest** [comment]
Eğer arama sonucu gelmeden hızlı davranıp entera basarsam bu sefer başlık açma bölümüne gidebiliyorum. :)

**Comment by erayarslan** [comment]
içine mi doğdu bilmiyorum ama bayadır aklımdaydı bu ve tam da şimdi onun commitini atmıştım.

@c2adac7006dbb23c88960fecfe65e27d1a0ca53c

**Comment by ozziest** [comment]
Galp galbe garşıymış. ❤️

**Comment by erayarslan** [comment]
düzgün hali canlıdadır 👍

**Comment by erayarslan** [comment]
hala küçük bir bug var sanırım, tekrar bakıyorum

**Comment by erayarslan** [comment]
ve [tamam](https://github.com/sausozluk/web/commit/a259a7bc1457b33db1b35a56d22205af2b231836) 😄
