### ISSUE TITLE
Pagination Hatası

### ISSUE THREAD

**Issue by ozziest** [sausozluk/api#46]
Yeni bir entry girdikten sonra, eklenen kayıt yeni bir sayfa eklenmesine yol açtığında, sayfalama verileri otomatik olarak değişmiyor. Az önce 4 sayfalık veri varken ardı ardına bir sürü entry girdim (e manyağım ya), sayfa sayısı 10'a çıkmasına rağmen hala 4 gözüküyordu.

**Comment by erayarslan** [comment]
Ekstradan onun için istek atmak yerine olduğu sayfaya anlık append ediyorum.
Son sayfaya da gidebilirim ya da yenileyebilirim de ama performans için böyle şey etmiştim.
Hangisi mantıklı sizce?

@okan @ozziest

**Comment by okan** [comment]
bence topic sayfası yerine entrynin sayfasına gitmek daha mantıklı. mesela create edilen entry 155 id'li olsun. eklemeden sonra <URL>/entry/155 adresine yönlendirelim. isterse başlığa da gider sonrasında. ikinci yol da fena görünmüyor (en son sayfaya yönlendirme)

**Comment by erayarslan** [comment]
@okan ın çözümü benim de aklıma yattı açıkçası.
update entry'le aynı mantık.

**Comment by erayarslan** [comment]
[done](https://github.com/sausozluk/web/commit/e54c5cf841ca13b22f59da60430d1eca674dac86)
