### ISSUE TITLE
Başlık uzunluğu sorunsalı

### ISSUE THREAD

**Issue by ozziest** [sausozluk/api#47]
Hata değilde merak ediyorum. Bir başlığa bknz verdiğimde dilediğim kadar uzun yazabiliyorum. Ancak o başlık 50 karakterden uzunsa içine entry giremiyorum. Bu normal mi? bknz'lara da sınır konulabilmesi makul olabilir.

**Comment by erayarslan** [comment]
İnsanlar bazen tanıp yapmaya üşenip bkz kullandıkları için genelde sözlük formatlarında bkz lar limitlenmiyor diye biliyorum.
Ve bence de limitlenmesin.
Yine de oy birliğiyle kabul edilirse çekerim emaneti sizi mi kırcam 😄

**Comment by okan** [comment]
evet, her bkz bir başlığa hit etmek zorunda değil aslında. o yüzden bence de kalabilir. 😌
